//! Charades' rules and data, free of UI: the word decks and the locale they come from, which words
//! a round deals so none repeats until its deck is used up, a round's clock and score, and reading
//! a nod or a tip back from the accelerometer.

use std::collections::{BTreeMap, BTreeSet};

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Decks
// ---------------------------------------------------------------------------

// `LOCALES`: every `words/<locale>/<deck>.txt`, generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/words.rs"));

/// The locale every other one falls back to.
pub const FALLBACK: &str = "en";

/// The order decks are offered in. A deck a locale adds that is not listed here follows these,
/// alphabetically by id.
pub const ORDER: &[&str] = &[
    "animals",
    "food",
    "act-it-out",
    "household",
    "jobs",
    "sports",
    "places",
    "movies",
    "characters",
    "history",
    "music",
    "science",
    "kids",
    "myths",
    "hobbies",
    "sayings",
    "celebrations",
    "feelings",
    "technology",
    "getting-around",
    "wardrobe",
];

/// One deck: its id (shared across locales, and what saved progress is keyed by), the title and
/// one-line description in the deck's own language, and its entries in file order.
#[derive(Clone, Debug, PartialEq)]
pub struct Deck {
    pub id: &'static str,
    pub title: String,
    pub blurb: String,
    pub words: Vec<String>,
}

/// Read one deck file: `# title:` and `# blurb:` header lines, other `#` lines as comments, blank
/// lines skipped, and one entry per remaining line.
pub fn parse_deck(id: &'static str, text: &str) -> Deck {
    let mut title = String::new();
    let mut blurb = String::new();
    let mut words = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if let Some(comment) = line.strip_prefix('#') {
            let comment = comment.trim();
            if let Some(t) = comment.strip_prefix("title:") {
                title = t.trim().to_string();
            } else if let Some(b) = comment.strip_prefix("blurb:") {
                blurb = b.trim().to_string();
            }
        } else if !line.is_empty() {
            words.push(line.to_string());
        }
    }
    if title.is_empty() {
        title = id.to_string();
    }
    Deck {
        id,
        title,
        blurb,
        words,
    }
}

/// The word-list locale that serves `wanted`: the exact tag, else its language, else
/// [`FALLBACK`]. `"fr-CA"` finds `fr-CA`, then `fr`, then `en`.
pub fn resolve_locale(wanted: &str) -> &'static str {
    let wanted = wanted.replace('_', "-");
    let base = wanted.split("-u-").next().unwrap_or(&wanted);
    let language = base.split('-').next().unwrap_or(base);
    for candidate in [base, language] {
        if let Some((l, _)) = LOCALES
            .iter()
            .find(|(l, _)| l.eq_ignore_ascii_case(candidate))
        {
            return l;
        }
    }
    // The UI also serves Apple's/browser Chinese tags from its zh-CN catalog.
    if language.eq_ignore_ascii_case("zh") {
        return "zh-CN";
    }
    FALLBACK
}

/// Every deck of `locale` (a tag [`resolve_locale`] returned), in [`ORDER`].
pub fn decks(locale: &str) -> Vec<Deck> {
    let Some((_, files)) = LOCALES.iter().find(|(l, _)| *l == locale) else {
        return Vec::new();
    };
    let mut out: Vec<Deck> = files
        .iter()
        .map(|(id, text)| parse_deck(id, text))
        .collect();
    let rank = |id: &str| ORDER.iter().position(|o| *o == id).unwrap_or(ORDER.len());
    out.sort_by(|a, b| rank(a.id).cmp(&rank(b.id)).then(a.id.cmp(b.id)));
    out
}

// ---------------------------------------------------------------------------
// Dealing without repeats
// ---------------------------------------------------------------------------

/// A small xorshift, so a deck's order is reproducible from its seed.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        x
    }
}

/// The deck's words `0..n` in the order `seed` shuffles them.
pub fn shuffled(n: usize, seed: u64) -> Vec<usize> {
    let mut order: Vec<usize> = (0..n).collect();
    let mut rng = Rng(seed | 1);
    for i in (1..n).rev() {
        let j = (rng.next() % (i as u64 + 1)) as usize;
        order.swap(i, j);
    }
    order
}

/// Where one deck's shuffled order has got to.
#[derive(Clone, Copy, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct DeckPos {
    pub seed: u64,
    pub next: usize,
}

/// Every deck's place in its order, per word-list locale and deck id, persisted so a word comes
/// back only after the rest of its deck has been played.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Rotation {
    pub decks: BTreeMap<String, DeckPos>,
}

impl Rotation {
    fn key(locale: &str, deck: &str) -> String {
        format!("{locale}/{deck}")
    }

    /// The deck's words in the order a round meets them: what is left of the current shuffle,
    /// then a fresh shuffle (from `fresh_seed`) of the words that part did not already hold.
    pub fn deal(&mut self, locale: &str, deck: &str, n: usize, fresh_seed: u64) -> Vec<usize> {
        let pos = self
            .decks
            .entry(Self::key(locale, deck))
            .or_insert(DeckPos {
                seed: fresh_seed,
                next: 0,
            });
        if pos.next >= n {
            *pos = DeckPos {
                seed: fresh_seed,
                next: 0,
            };
        }
        let mut out: Vec<usize> = shuffled(n, pos.seed)[pos.next..].to_vec();
        let taken: BTreeSet<usize> = out.iter().copied().collect();
        out.extend(
            shuffled(n, fresh_seed ^ 0x9E37_79B9)
                .into_iter()
                .filter(|i| !taken.contains(i)),
        );
        out
    }

    /// Record that a round showed `used` of the words [`Rotation::deal`] gave it. Past the end of
    /// the current shuffle, the deck moves on to the shuffle `deal` continued with.
    pub fn commit(&mut self, locale: &str, deck: &str, n: usize, fresh_seed: u64, used: usize) {
        let pos = self.decks.entry(Self::key(locale, deck)).or_default();
        let left = n.saturating_sub(pos.next);
        if used < left {
            pos.next += used;
            return;
        }
        // The round ran into the continuation, which skipped the words the old shuffle still
        // held: the new shuffle resumes after the last word the round took from it.
        let tail: BTreeSet<usize> = shuffled(n, pos.seed)[pos.next.min(n)..]
            .iter()
            .copied()
            .collect();
        let seed = fresh_seed ^ 0x9E37_79B9;
        let mut from_new = used - left;
        let mut next = 0;
        for (i, w) in shuffled(n, seed).into_iter().enumerate() {
            if from_new == 0 {
                break;
            }
            if !tail.contains(&w) {
                from_new -= 1;
            }
            next = i + 1;
        }
        *pos = DeckPos { seed, next };
    }
}

// ---------------------------------------------------------------------------
// A round
// ---------------------------------------------------------------------------

/// How a card was answered.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Mark {
    Correct,
    Pass,
}

/// One round: the words in the order they come up, what was answered, and the clock.
#[derive(Clone, Debug)]
pub struct Round {
    pub queue: Vec<String>,
    /// How many of `queue` have been shown, the current card included.
    pub shown: usize,
    pub results: Vec<(String, Mark)>,
    pub length: f64,
    pub elapsed: f64,
}

/// What a step of the clock crossed.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Beat {
    /// A whole second of the last ones went by (the value is the seconds left).
    Warning(u32),
    /// The time ran out.
    TimeUp,
}

/// The warning ticks start this many seconds from the end.
pub const WARN_FROM: u32 = 10;

impl Round {
    pub fn new(queue: Vec<String>, length: f64) -> Round {
        let shown = usize::from(!queue.is_empty());
        Round {
            queue,
            shown,
            results: Vec::new(),
            length,
            elapsed: 0.0,
        }
    }

    /// The card showing, or `None` once the deck ran out.
    pub fn current(&self) -> Option<&str> {
        if self.shown == 0 || self.results.len() >= self.shown {
            return None;
        }
        self.queue.get(self.shown - 1).map(String::as_str)
    }

    /// Answer the current card and deal the next. Returns false when nothing was showing.
    pub fn answer(&mut self, mark: Mark) -> bool {
        let Some(word) = self.current().map(str::to_string) else {
            return false;
        };
        self.results.push((word, mark));
        if self.shown < self.queue.len() {
            self.shown += 1;
        }
        true
    }

    pub fn remaining(&self) -> f64 {
        (self.length - self.elapsed).max(0.0)
    }

    pub fn over(&self) -> bool {
        self.remaining() <= 0.0 || self.current().is_none()
    }

    pub fn score(&self) -> usize {
        self.results
            .iter()
            .filter(|(_, m)| *m == Mark::Correct)
            .count()
    }

    /// Advance the clock by `dt` seconds and report what it crossed.
    pub fn tick(&mut self, dt: f64) -> Option<Beat> {
        if self.remaining() <= 0.0 {
            return None;
        }
        let before = self.remaining();
        self.elapsed += dt.max(0.0);
        let after = self.remaining();
        if after <= 0.0 {
            return Some(Beat::TimeUp);
        }
        let (b, a) = (before.ceil() as u32, after.ceil() as u32);
        (a < b && a <= WARN_FROM).then_some(Beat::Warning(a))
    }

    /// How many words the round put in front of the players, for [`Rotation::commit`].
    pub fn used(&self) -> usize {
        self.shown
    }
}

// ---------------------------------------------------------------------------
// Reading a nod
// ---------------------------------------------------------------------------

/// Which way an accelerometer's axes point relative to gravity. CoreMotion reports the pull of
/// gravity (a phone lying face up reads z ≈ −9.8), Android, HarmonyOS and the W3C web the
/// opposite (z ≈ +9.8); see docs/sensors.md.
pub fn native_sign() -> f64 {
    if cfg!(target_os = "ios") { 1.0 } else { -1.0 }
}

/// The sign that makes `reading` point toward the floor, judged from a moment the screen faced up
/// (the player looking at it): face up, the floor is behind the screen, at −z. `None` when the
/// phone was too close to upright to tell.
pub fn sign_from_face_up(reading: [f64; 3]) -> Option<f64> {
    (reading[2].abs() > 4.0).then(|| -reading[2].signum())
}

/// What a tilt means.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Gesture {
    /// The screen turned toward the floor: a nod, for "got it".
    Down,
    /// The screen turned toward the ceiling: a tip back, for "pass".
    Up,
}

/// Past this many degrees from the neutral pose a tilt counts.
pub const TRIGGER_DEG: f64 = 40.0;
/// Within this many degrees of neutral the phone is back in place.
pub const REARM_DEG: f64 = 22.0;
/// How long the phone has to stay back in place before the next tilt counts.
pub const REARM_HOLD: f64 = 0.25;
/// The neutral pose is measured at the start of a round, within this far of upright.
pub const MAX_BASELINE_DEG: f64 = 30.0;

/// Turns accelerometer samples into nods and tip-backs. The phone sits upright on the forehead,
/// screen facing the other players; the angle that matters is how far the screen has turned
/// toward the floor, whichever way round the phone is held.
#[derive(Clone, Debug)]
pub struct Tilt {
    sign: f64,
    /// Gravity's direction in the phone's axes, smoothed, unit length.
    down: Option<[f64; 3]>,
    baseline: f64,
    armed: bool,
    back_for: f64,
}

impl Tilt {
    pub fn new(sign: f64) -> Tilt {
        Tilt {
            sign,
            down: None,
            baseline: 0.0,
            armed: true,
            back_for: 0.0,
        }
    }

    /// Take one sample `dt` seconds after the last, and report a gesture it completes.
    pub fn feed(&mut self, reading: [f64; 3], dt: f64) -> Option<Gesture> {
        let g =
            (reading[0] * reading[0] + reading[1] * reading[1] + reading[2] * reading[2]).sqrt();
        // A jolt or a drop says nothing about which way the phone faces.
        if !(4.0..=16.0).contains(&g) {
            return None;
        }
        let raw = reading.map(|v| self.sign * v / g);
        let down = match self.down {
            None => raw,
            Some(prev) => {
                let mixed = [0, 1, 2].map(|i| prev[i] + 0.55 * (raw[i] - prev[i]));
                let n = (mixed[0] * mixed[0] + mixed[1] * mixed[1] + mixed[2] * mixed[2]).sqrt();
                mixed.map(|v| v / n.max(1e-9))
            }
        };
        self.down = Some(down);
        let angle = self.angle().unwrap_or(0.0);
        if self.armed {
            if angle >= TRIGGER_DEG {
                self.armed = false;
                self.back_for = 0.0;
                return Some(Gesture::Down);
            }
            if angle <= -TRIGGER_DEG {
                self.armed = false;
                self.back_for = 0.0;
                return Some(Gesture::Up);
            }
        } else if angle.abs() <= REARM_DEG {
            self.back_for += dt;
            if self.back_for >= REARM_HOLD {
                self.armed = true;
            }
        } else {
            self.back_for = 0.0;
        }
        None
    }

    /// Degrees the screen has turned toward the floor from the neutral pose (negative: toward
    /// the ceiling), once a sample has arrived.
    pub fn angle(&self) -> Option<f64> {
        self.raw_angle().map(|a| a - self.baseline)
    }

    fn raw_angle(&self) -> Option<f64> {
        self.down.map(|d| d[2].clamp(-1.0, 1.0).asin().to_degrees())
    }

    /// Make the current pose neutral, as a round starts. A pose far from upright is not what a
    /// phone on a forehead looks like, so the baseline never strays past [`MAX_BASELINE_DEG`].
    pub fn calibrate(&mut self) {
        self.baseline = self
            .raw_angle()
            .unwrap_or(0.0)
            .clamp(-MAX_BASELINE_DEG, MAX_BASELINE_DEG);
        self.armed = true;
        self.back_for = 0.0;
    }

    /// Whether the phone is held upright, screen facing out: the pose a round starts from.
    pub fn upright(&self) -> bool {
        self.raw_angle()
            .is_some_and(|a| a.abs() <= MAX_BASELINE_DEG)
    }

    /// Which way is down on the screen, as a quarter-turn count clockwise from the screen's own
    /// down (0: the bottom edge, 1: the left edge, 2: the top, 3: the right), when the phone is
    /// upright enough to tell.
    pub fn screen_down(&self) -> Option<u8> {
        let d = self.down?;
        // The screen's axes: x to the right, y up the screen.
        let (x, y) = (d[0], d[1]);
        let planar = (x * x + y * y).sqrt();
        if planar < 0.5 {
            return None;
        }
        Some(if y.abs() >= x.abs() {
            if y < 0.0 { 0 } else { 2 }
        } else if x < 0.0 {
            1
        } else {
            3
        })
    }
}

// ---------------------------------------------------------------------------
// Settings and records
// ---------------------------------------------------------------------------

/// The round lengths on offer, in seconds.
pub const LENGTHS: [u32; 4] = [30, 60, 90, 120];

fn on() -> bool {
    true
}

fn sixty() -> u32 {
    60
}

/// This game's settings: gamekit's switches, the round length, and whether a tilt answers.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Settings {
    #[serde(default = "on")]
    pub sounds: bool,
    #[serde(default = "on")]
    pub vibrations: bool,
    #[serde(default)]
    pub instructions_shown: bool,
    #[serde(default = "sixty")]
    pub round_secs: u32,
    #[serde(default = "on")]
    pub tilt: bool,
}

impl Default for Settings {
    fn default() -> Self {
        Settings {
            sounds: true,
            vibrations: true,
            instructions_shown: false,
            round_secs: 60,
            tilt: true,
        }
    }
}

/// Rounds played and the best score, per deck id.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Records {
    pub played: BTreeMap<String, u32>,
    pub best: BTreeMap<String, u32>,
}

impl Records {
    /// Count a round; true when it set the deck's best score.
    pub fn record(&mut self, deck: &str, score: u32) -> bool {
        *self.played.entry(deck.to_string()).or_default() += 1;
        let best = self.best.entry(deck.to_string()).or_default();
        if score > *best {
            *best = score;
            true
        } else {
            false
        }
    }

    pub fn best(&self, deck: &str) -> u32 {
        self.best.get(deck).copied().unwrap_or(0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const G: f64 = 9.81;

    /// An Android-convention reading (z = +g face up) for a phone held landscape and upright,
    /// screen out, then turned `deg` toward the floor.
    fn android_upright(deg: f64) -> [f64; 3] {
        let r = deg.to_radians();
        // Down points along −x in landscape; turning the screen floorward moves it into +z.
        let down = [-r.cos(), 0.0, r.sin()];
        down.map(|v| -v * G)
    }

    fn feed_steady(t: &mut Tilt, reading: [f64; 3], secs: f64) -> Vec<Gesture> {
        let mut out = Vec::new();
        let steps = (secs / 0.05).round() as usize;
        for _ in 0..steps {
            out.extend(t.feed(reading, 0.05));
        }
        out
    }

    #[test]
    fn every_deck_is_well_formed() {
        assert!(LOCALES.iter().any(|(l, _)| *l == FALLBACK));
        for (locale, files) in LOCALES {
            for deck in decks(locale) {
                let where_ = format!("{locale}/{}", deck.id);
                assert!(
                    !deck.title.is_empty() && deck.title != deck.id,
                    "{where_}: no title"
                );
                assert!(!deck.blurb.is_empty(), "{where_}: no blurb");
                assert!(
                    deck.words.len() >= 100,
                    "{where_}: {} words",
                    deck.words.len()
                );
                let mut seen = BTreeSet::new();
                for w in &deck.words {
                    assert!(
                        seen.insert(w.to_lowercase()),
                        "{where_}: \"{w}\" is listed twice"
                    );
                    assert!(w.chars().count() <= 40, "{where_}: \"{w}\" is too long");
                    assert_eq!(w.trim(), w, "{where_}: \"{w}\" has stray spaces");
                }
            }
            assert_eq!(decks(locale).len(), files.len());
        }
    }

    #[test]
    fn the_english_corpus_is_large() {
        let total: usize = decks(FALLBACK).iter().map(|d| d.words.len()).sum();
        assert!(decks(FALLBACK).len() >= 20);
        assert!(total >= 3000, "{total} entries");
    }

    #[test]
    fn locales_fall_back_by_language_then_to_english() {
        assert_eq!(resolve_locale("en"), "en");
        assert_eq!(resolve_locale("en-GB"), "en");
        assert_eq!(resolve_locale("en_US"), "en");
        assert_eq!(resolve_locale("xx-YY"), FALLBACK);
        assert_eq!(resolve_locale("en-u-co-phonebk"), "en");
        assert_eq!(resolve_locale("fr-CA"), "fr");
        assert_eq!(resolve_locale("pt_BR"), "pt-BR");
        assert_eq!(resolve_locale("zh-CN"), "zh-CN");
        assert_eq!(resolve_locale("zh-Hans-CN"), "zh-CN");
        assert_eq!(resolve_locale("zh-Hans"), "zh-CN");
    }

    #[test]
    fn decks_come_in_the_listed_order() {
        let ids: Vec<&str> = decks(FALLBACK).iter().map(|d| d.id).collect();
        let listed: Vec<&str> = ORDER.iter().copied().filter(|o| ids.contains(o)).collect();
        assert_eq!(&ids[..listed.len()], &listed[..]);
    }

    #[test]
    fn parsing_reads_headers_and_skips_comments() {
        let d = parse_deck(
            "x",
            "# title: Things\n# blurb: Stuff\n# a note\n\n  cup \nbowl\n",
        );
        assert_eq!(d.title, "Things");
        assert_eq!(d.blurb, "Stuff");
        assert_eq!(d.words, vec!["cup", "bowl"]);
    }

    #[test]
    fn a_deck_repeats_nothing_until_it_is_used_up() {
        let n = 25;
        let mut rot = Rotation::default();
        let mut seen = Vec::new();
        let mut seed = 11;
        while seen.len() < n {
            let queue = rot.deal("en", "animals", n, seed);
            let used = 7.min(n - seen.len());
            seen.extend_from_slice(&queue[..used]);
            rot.commit("en", "animals", n, seed, used);
            seed = seed.wrapping_mul(31).wrapping_add(7);
        }
        let distinct: BTreeSet<usize> = seen.iter().copied().collect();
        assert_eq!(distinct.len(), n, "every word once before any repeats");
    }

    #[test]
    fn a_round_running_past_the_deck_continues_without_repeats() {
        let n = 10;
        let mut rot = Rotation::default();
        let first = rot.deal("en", "d", n, 1);
        rot.commit("en", "d", n, 1, 8);
        let queue = rot.deal("en", "d", n, 2);
        assert_eq!(
            queue.len(),
            n,
            "the rest of this shuffle, then the words it lacked"
        );
        let distinct: BTreeSet<usize> = queue.iter().copied().collect();
        assert_eq!(distinct.len(), n);
        assert_eq!(&queue[..2], &first[8..]);
        // Using five: the two left, then three of the new shuffle, which must not come round again
        // before that shuffle is through.
        rot.commit("en", "d", n, 2, 5);
        let rest = n - rot.decks["en/d"].next;
        let next = rot.deal("en", "d", n, 3);
        assert!(!next[..rest].iter().any(|i| queue[2..5].contains(i)));
    }

    #[test]
    fn a_round_scores_and_ends() {
        let mut r = Round::new(vec!["cat".into(), "dog".into(), "cow".into()], 60.0);
        assert_eq!(r.current(), Some("cat"));
        assert!(r.answer(Mark::Correct));
        assert_eq!(r.current(), Some("dog"));
        assert!(r.answer(Mark::Pass));
        assert!(r.answer(Mark::Correct));
        assert_eq!(r.current(), None, "the deck ran out");
        assert!(r.over());
        assert!(!r.answer(Mark::Correct));
        assert_eq!(r.score(), 2);
        assert_eq!(r.used(), 3);
    }

    #[test]
    fn the_clock_warns_through_the_last_seconds_then_ends() {
        let mut r = Round::new(vec!["a".into()], 12.0);
        let mut beats = Vec::new();
        for _ in 0..(13 * 20) {
            if let Some(b) = r.tick(0.05) {
                beats.push(b);
            }
        }
        let warnings: Vec<u32> = beats
            .iter()
            .filter_map(|b| match b {
                Beat::Warning(s) => Some(*s),
                Beat::TimeUp => None,
            })
            .collect();
        assert_eq!(warnings, (1..=10).rev().collect::<Vec<_>>());
        assert_eq!(beats.last(), Some(&Beat::TimeUp));
        assert_eq!(beats.iter().filter(|b| **b == Beat::TimeUp).count(), 1);
    }

    #[test]
    fn a_nod_is_correct_and_a_tip_back_is_pass() {
        let mut t = Tilt::new(-1.0);
        assert!(feed_steady(&mut t, android_upright(0.0), 0.5).is_empty());
        assert!(t.upright());
        t.calibrate();
        assert_eq!(
            feed_steady(&mut t, android_upright(60.0), 0.3),
            [Gesture::Down]
        );
        // Holding the nod counts once.
        assert!(feed_steady(&mut t, android_upright(65.0), 1.0).is_empty());
        assert!(feed_steady(&mut t, android_upright(5.0), 0.5).is_empty());
        assert_eq!(
            feed_steady(&mut t, android_upright(-60.0), 0.3),
            [Gesture::Up]
        );
    }

    #[test]
    fn a_brief_return_does_not_rearm() {
        let mut t = Tilt::new(-1.0);
        feed_steady(&mut t, android_upright(0.0), 0.3);
        t.calibrate();
        assert_eq!(
            feed_steady(&mut t, android_upright(60.0), 0.2),
            [Gesture::Down]
        );
        // Passing through neutral on the way to the other side is not a return.
        assert!(feed_steady(&mut t, android_upright(0.0), 0.1).is_empty());
        assert!(feed_steady(&mut t, android_upright(60.0), 0.3).is_empty());
    }

    #[test]
    fn small_wobbles_count_for_nothing() {
        let mut t = Tilt::new(-1.0);
        feed_steady(&mut t, android_upright(0.0), 0.3);
        t.calibrate();
        for deg in [10.0, -15.0, 25.0, -30.0, 35.0, -35.0] {
            assert!(
                feed_steady(&mut t, android_upright(deg), 0.3).is_empty(),
                "{deg}°"
            );
        }
    }

    #[test]
    fn the_neutral_pose_is_whatever_the_player_starts_from() {
        let mut t = Tilt::new(-1.0);
        // Worn leaning back a little.
        feed_steady(&mut t, android_upright(-20.0), 0.5);
        t.calibrate();
        assert!(
            feed_steady(&mut t, android_upright(15.0), 0.3).is_empty(),
            "35° from neutral"
        );
        assert_eq!(
            feed_steady(&mut t, android_upright(25.0), 0.3),
            [Gesture::Down]
        );
    }

    #[test]
    fn ios_readings_mean_the_same_with_their_own_sign() {
        let mut t = Tilt::new(1.0);
        let ios = |deg: f64| android_upright(deg).map(|v| -v);
        feed_steady(&mut t, ios(0.0), 0.3);
        t.calibrate();
        assert_eq!(feed_steady(&mut t, ios(60.0), 0.3), [Gesture::Down]);
    }

    #[test]
    fn either_landscape_way_round_reads_alike() {
        let mut t = Tilt::new(-1.0);
        let flipped = |deg: f64| {
            let r = android_upright(deg);
            [-r[0], r[1], r[2]]
        };
        feed_steady(&mut t, flipped(0.0), 0.3);
        t.calibrate();
        assert_eq!(feed_steady(&mut t, flipped(-55.0), 0.3), [Gesture::Up]);
    }

    #[test]
    fn a_jolt_is_ignored() {
        let mut t = Tilt::new(-1.0);
        feed_steady(&mut t, android_upright(0.0), 0.3);
        t.calibrate();
        assert!(t.feed([0.0, 0.0, 30.0], 0.05).is_none());
        assert!(t.feed([0.0, 0.0, 0.5], 0.05).is_none());
        assert!(t.angle().is_some_and(|a| a.abs() < 5.0));
    }

    #[test]
    fn the_face_up_sign_matches_each_convention() {
        assert_eq!(
            sign_from_face_up([0.0, 3.0, 9.0]),
            Some(-1.0),
            "Android face up"
        );
        assert_eq!(
            sign_from_face_up([0.0, -3.0, -9.0]),
            Some(1.0),
            "iOS face up"
        );
        assert_eq!(
            sign_from_face_up([9.8, 0.0, 1.0]),
            None,
            "upright tells nothing"
        );
    }

    #[test]
    fn screen_down_follows_the_held_edge() {
        let mut t = Tilt::new(-1.0);
        // Android: portrait, upright. Gravity pulls toward −y, the reading is +y.
        t.feed([0.0, G, 0.0], 0.05);
        assert_eq!(t.screen_down(), Some(0));
        let mut t = Tilt::new(-1.0);
        // Landscape with the left edge down: the pull is toward −x, the reading +x.
        t.feed([G, 0.0, 0.0], 0.05);
        assert_eq!(t.screen_down(), Some(1));
        let mut t = Tilt::new(-1.0);
        t.feed([0.0, 0.0, G], 0.05);
        assert_eq!(t.screen_down(), None, "flat: no edge is down");
    }

    #[test]
    fn records_keep_the_best() {
        let mut r = Records::default();
        assert!(r.record("animals", 5));
        assert!(!r.record("animals", 3));
        assert!(r.record("animals", 9));
        assert_eq!(r.best("animals"), 9);
        assert_eq!(r.played["animals"], 3);
    }
}
